### PR TITLE
Change Images BACK to PNG

### PR DESCRIPTION
**Pull request by Mark-Kerbin**
-Misread GD's message, coverted to Jpg. 
-Converted to png for reals this time.

### CODE REVIEW

**Comment by Gordon-Dry** [comment]
These two images are still technically jpeg:
Agent\KerbalAcademy.png
Agent\KerbalAcademy_scaled.png

The file header (first few bytes in ANSI):
ÿØÿà JFIF      ÿí „Photoshop 3.0 8BIM

Should start with:
‰PNG

**Comment by Mark-Kerbin** [comment]
Actually Im using MS paint... 
Any thoughts on how one might make it work correctly?

**Comment by Gordon-Dry** [comment]
Well, everybody has another taste, but for file viewing, screenshots and quick conversion I use https://www.xnview.com/en/xnviewmp/

**Comment by Mark-Kerbin** [comment]
Ok so all images are now actually png files. I think

**Pull request merged**
